version: '3.4'

services:
  ipfs-host0:
    container_name: ipfs-host0
    image: ipfs/go-ipfs:latest
    environment:
      - ipfs_staging=~/Downloads/stage0
      - ipfs_data=~/Downloads/data0
    ports:
      - 4001:4001
      - 4001:4001/udp
      - 8080:8080
      - 5051:5001

  ipfs-host1:
    container_name: ipfs-host1
    image: ipfs/go-ipfs:latest
    environment:
      - ipfs_staging=~/Downloads/stage1
      - ipfs_data=~/Downloads/data1
    ports:
      - 4002:4001
      - 4002:4001/udp
      - 8081:8080
      - 5052:5001

  ipfs-host2:
    container_name: ipfs-host2
    image: ipfs/go-ipfs:latest
    environment:
      - ipfs_staging=~/Downloads/stage2
      - ipfs_data=~/Downloads/data2
    ports:
      - 4003:4001
      - 4003:4001/udp
      - 8082:8080
      - 5053:5001

  ipfs-host3:
    container_name: ipfs-host3
    image: ipfs/go-ipfs:latest
    environment:
      - ipfs_staging=~/Downloads/stage3
      - ipfs_data=~/Downloads/data3
    ports:
      - 4004:4001
      - 4004:4001/udp
      - 8084:8080
      - 5054:5001

  ipfs-host4:
    container_name: ipfs-host4
    image: ipfs/go-ipfs:latest
    environment:
      - ipfs_staging=~/Downloads/stage4
      - ipfs_data=~/Downloads/data4
    ports:
      - 4005:4001
      - 4005:4001/udp
      - 8085:8080
      - 5055:5001

  ipfs-host5:
    container_name: ipfs-host5
    image: ipfs/go-ipfs:latest
    environment:
      - ipfs_staging=~/Downloads/stage5
      - ipfs_data=~/Downloads/data5
    ports:
      - 4006:4001
      - 4006:4001/udp
      - 8086:8080
      - 5056:5001

  ipfs-host6:
    container_name: ipfs-host6
    image: ipfs/go-ipfs:latest
    environment:
      - ipfs_staging=~/Downloads/stage6
      - ipfs_data=~/Downloads/data6
    ports:
      - 4007:4001
      - 4007:4001/udp
      - 8087:8080
      - 5057:5001

  ipfs-host7:
    container_name: ipfs-host7
    image: ipfs/go-ipfs:latest
    environment:
      - ipfs_staging=~/Downloads/stage7
      - ipfs_data=~/Downloads/data7
    ports:
      - 4008:4001
      - 4008:4001/udp
      - 8088:8080
      - 5058:5001

  ipfs-host8:
    container_name: ipfs-host8
    image: ipfs/go-ipfs:latest
    environment:
      - ipfs_staging=~/Downloads/stage8
      - ipfs_data=~/Downloads/data8
    ports:
      - 4009:4001
      - 4009:4001/udp
      - 8089:8080
      - 5059:5001